pairs:
  - ETHUSDT
  - BTCUSDT
  - AVAXUSDT
  - BNBUSDT

intervals:
  - 1m
  - 5m
  - 15m
  - 30m

redis_port: 6379
redis_host: "172.17.0.2"

binance_kline_url: "wss://stream.binance.com:9443/ws"
candle_websocket_port: "4444"
candle_websocket_url: "localhost"

binance_tick_url : "wss://stream.binance.com:9443/ws"
tick_data_port : "4445"
tick_data_url : "localhost"

