version: '3'

services:
  tick_data_websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust port mapping as needed

  live_candle_websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Adjust port mapping as needed
