version: '3'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust port mapping as needed
    volumes:
      - ./live_candle_websocket_api.py:/app/live_candle_websocket_api.py
      - ./commons.py:/app/commons.py